### ISSUE TITLE
无法编译

### ISSUE THREAD

**Issue by rmtic** [kaku2015/ColorfulNews#2]
Error:Execution failed for task ':app:transformResourcesWithMergeJavaResForDebug'.

> com.android.build.api.transform.TransformException: com.android.builder.packaging.DuplicateFileException: Duplicate files copied in APK META-INF/NOTICE
>     File1: C:\Users\rmtic.gradle\caches\modules-2\files-2.1\com.fasterxml.jackson.core\jackson-core\2.7.2\8b8310381b690e317f5f0574e9b2dd7034778b4c\jackson-core-2.7.2.jar
>     File2: C:\Users\rmtic.gradle\caches\modules-2\files-2.1\com.fasterxml.jackson.core\jackson-databind\2.7.2\84ffa765dd258dbab8695963c41308b054f3a1cb\jackson-databind-2.7.2.jar

**Comment by kaku2015** [comment]
好像是你的工程下有重复文件的原因吧...
