### ISSUE TITLE
大神你好，能不能请教一下，新闻的url 怎么得到的？

### ISSUE THREAD

**Issue by uty3714** [kaku2015/ColorfulNews#4]
就是网易新闻的url 大神是如何抓取出来的呀？可以分享一下吗？

**Comment by uty3714** [comment]
赞一下 写的app 很棒。。

**Comment by kaku2015** [comment]
谢谢，我也是参照别人的，应该是用爬虫吧，具体我也没有研究过... @uty3714

**Comment by uty3714** [comment]
谢谢，我现在在看大神你的这个源码。。

**Comment by kaku2015** [comment]
大神不敢当⊙﹏⊙‖∣，我也是学习，互相学习o(∩_∩)o
