### ISSUE TITLE
适配问题

### ISSUE THREAD

**Issue by gzfgeh** [kaku2015/ColorfulNews#6]
我想问一下作者适配问题怎么处理的？谢谢

**Comment by ZengChong500373** [comment]
兄弟，我想问下。。你获取每个新闻的详情的时候，他的key是变化的，值不变。。你是怎么做的啊？如果方便可以+个qq吗

**Comment by kaku2015** [comment]
@gzfgeh 这个项目没有怎么特别处理过适配问题，沉浸栏你可以参考下代码
